version: '3.1'

services:
  client: 
    network_mode: host
    container_name: 'magneto-client'
    restart: 'always'
    build:
      context: ./client
      dockerfile: Dockerfile

  node: 
    network_mode: host
    restart: 'always'
    build:
      context: ./server
      dockerfile: Dockerfile
