version: '3.1'

services:
  client: 
    network_mode: host
    container_name: 'magneto-client'
    restart: 'always'
    build:
      context: ./client
      dockerfile: Dockerfile

  server: 
    network_mode: host
    container_name: 'magneto-db'
    restart: 'always'
    build:
      context: ./server
      dockerfile: Dockerfile
    ports: 
      - 5678:5678
    expose:
      - 5678