version: '3.1'

services:
  server: 
    network_mode: host
    container_name: 'magneto-db'
    restart: 'always'
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 5678:5678
    expose:
      - 5678