version: '3.1'

services:
  node0: 
    container_name: 'magneto-db'
    restart: 'always'
    build:
      context: .
      dockerfile: Dockerfile
    command:  ["java", "-jar", "/app/magneto-db.jar", "5670"]