/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package magneto.db;

import java.io.IOException;

import magneto.db.server.MagnetoServer;

public class App {
    public static void main(String[] args) throws IOException {
        MagnetoServer.main(args);
    }
}
